# Generated by Django 3.2.16 on 2022-12-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_orders_details_back_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
