# Generated by Django 3.2.16 on 2022-12-14 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_products_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalProducts',
            fields=[
                ('desc', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('discount_price', models.PositiveIntegerField()),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.categories')),
            ],
        ),
    ]
